version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
  graphite:
    build: ./graphite
    ports:
      - "2003:2003"
    volumes:
      - "./data/whisper:/opt/graphite/storage/whisper"
      - "./log/graphite:/opt/graphite/storage/log"
  grafana:
    image: grafana/grafana
  statsd:
    build: ./statsd
    ports:
      - '8125:8125/udp'
      - '8126:8126'